Add HTTP health server (closes #115) (#227)
* Add HTTP health server (closes #115)

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* PR feedback

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* More PR feedback

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Fix DaemonModeFlagName const

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Make health check path configurable and implement default health check configs

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Keep ParseConfigFile in main

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Fix tests

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Upgrade golangci-lint to fix error
Error: can't load config: the Go language version (go1.22) used to build golangci-lint is lower than the targeted Go version (1.23.3)

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update cmd/spiffe-helper/config/config.go

Co-authored-by: Faisal Memon <fymemon@yahoo.com>
Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update README.md

Co-authored-by: Faisal Memon <fymemon@yahoo.com>
Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Fix remaining config renames

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Add back flag duplication

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Don't use a pointer for HealthCheckConfig

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Remove global variable

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Avoid passing entire HCL config into health check, simplify status JSON

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update cmd/spiffe-helper/config/config.go

Co-authored-by: Faisal Memon <fymemon@yahoo.com>
Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update pkg/health/health.go

Co-authored-by: Faisal Memon <fymemon@yahoo.com>
Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update cmd/spiffe-helper/main.go

Co-authored-by: Faisal Memon <fymemon@yahoo.com>
Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Add missing X509WriteSuccess check

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Add JSON marshalling tags

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Lint fixes

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* More PR feedback changes

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Lint fixes

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update pkg/sidecar/sidecar.go

Co-authored-by: Faisal Memon <fymemon@yahoo.com>
Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update pkg/sidecar/sidecar.go

Co-authored-by: Faisal Memon <fymemon@yahoo.com>
Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update pkg/sidecar/sidecar.go

Co-authored-by: Faisal Memon <fymemon@yahoo.com>
Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update pkg/sidecar/sidecar.go

Co-authored-by: Faisal Memon <fymemon@yahoo.com>
Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update pkg/sidecar/sidecar_test.go

Co-authored-by: Faisal Memon <fymemon@yahoo.com>
Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update pkg/sidecar/sidecar.go

Co-authored-by: Faisal Memon <fymemon@yahoo.com>
Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update pkg/sidecar/sidecar.go

Co-authored-by: Faisal Memon <fymemon@yahoo.com>
Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update pkg/sidecar/sidecar.go

Co-authored-by: Faisal Memon <fymemon@yahoo.com>
Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update pkg/health/health.go

Co-authored-by: Faisal Memon <fymemon@yahoo.com>
Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Lint fixes

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Start sidecar after health server

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Create separate health endpoints for liveness and readiness

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Move StartHealthServer() into startSidecar()

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Lint fix

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Update readme

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Log when health server is starting

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Change Error response to also be JSON

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Refactoring

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* PR suggestions

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>

* Fix readme indents

---------

Signed-off-by: Keegan Witt <keeganwitt@gmail.com>
Co-authored-by: Faisal Memon <fymemon@yahoo.com>